### ISSUE TITLE
Faas-js-runtime auto-instrumentation

### ISSUE THREAD

**Issue by helio-frota** [obs-nebula/supernova#13]
And use with https://github.com/obs-nebula/function-five

**Comment by rdruss** [comment]
Any possible relationship to https://github.com/cloudevents/sdk-javascript/issues/355?

**Comment by helio-frota** [comment]
thanks @rdruss 

I was reading the thread and I found https://github.com/cloudevents/spec/blob/v1.0.1/extensions/distributed-tracing.md#using-the-distributed-tracing-extension

for the plugin I was thinking on start small focusing on the `http functions` https://github.com/obs-nebula/function-five, let's say "talking with each other" in a way that make it more complete-in-terms-of-trace-information because when doing manual tracing I got only the function name.

but yeah to help with communications we can start with the `HTTP function`
https://github.com/nodeshift/faas-js-runtime#handle-signature

```
HTTP Functions
The HTTP function signature is the simplest. It is invoked for every HTTP request that does not contain a CloudEvent.
```

and then move forward later to 

```
CloudEvent Functions
CloudEvent functions are used in environments where the incoming HTTP request is a CloudEvent.
```


:+1:
