### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by helio-frota** [obs-nebula/supernova#2]
Our main goal is to release the result of a test using https://github.com/Hyperfoil in an application that preferably contains a database, kafka, and an express back-end.

The project contains a Java example: https://github.com/Hyperfoil/vehicle-market
Maybe we can make a `clone` of this using JavaScript. :man_shrugging: 

But our organization is R&D by default, so we can't rule out possibilities of having different views of the same problem. In other words, is not good for us just finishing a requested task and... done.

So It would be good to have a set of functions containing manual instrumentation and run simple local benchmark tests at the function level. Also a basic test of an http endpoint with ~https://github.com/giltene/wrk2~ https://www.npmjs.com/package/autocannon would also be interesting.

* We need a repository for the Hyperfoil test.
* we need a repository for the function level test + endpoint test

**Comment by helio-frota** [comment]
> we need a repository for the function level test + endpoint test
repo created but contains nothing yet https://github.com/obs-nebula/perf-quest

**Comment by helio-frota** [comment]
I don't know how things works in OTEL for other runtimes/languages but for JS/TS we need to keep the focus on the auto-instrumentation sdks, manual-instrumentation sdk and the plugins.

They can be found here:
https://github.com/open-telemetry/opentelemetry-js/tree/main/packages
https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node

Because of this we are creating a demo that tries to use some of the plugins + the manual instrumentation for kafka.
https://github.com/obs-nebula/hyperfoil-test

**Comment by rdruss** [comment]
I would assume that you aren't testing all the auto-instrumentation plugins.  So, which OTEL plugins/sdks do you plan to test?

**Comment by helio-frota** [comment]
>  I would assume that you aren't testing all the auto-instrumentation plugins.

@rdruss that is correct :+1: 

> So, which OTEL plugins/sdks do you plan to test?

For the plugins:
* express ( https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-express )
* fastify ( https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-fastify )
* nestjs ( https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-nestjs-core ) 
* postgresql ( https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-pg )
* socketIO (https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/instrumentation-socket.io) -- this not 100% sure yet. 

For the SDKs (both auto and manual)
* https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-sdk-trace-base
* https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-sdk-trace-node

**Comment by helio-frota** [comment]
@rdruss test done :+1: 

OTEL-js disabled:
https://github.com/obs-nebula/hyperfoil-test#benchmark-with-hyperfoil

In other branch we have :

OTEL-js enabled:
https://github.com/obs-nebula/hyperfoil-test/tree/console_exporter#benchmark-with-hyperfoil-and-otel-js-enabled
